using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Mediator.SourceGenerator
{
    [Generator]
    public class MediatorGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. Find all classes that implement IRequestHandler<TRequest, TResponse>
            var handlerDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax { BaseList: not null },
                    transform: static (ctx, _) => GetHandlerInfo(ctx))
                .Where(static m => m is not null);

            // 2. Generate the source
            context.RegisterSourceOutput(handlerDeclarations.Collect(), Execute);
        }

        private static HandlerInfo? GetHandlerInfo(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var model = context.SemanticModel;
            var typeSymbol = model.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (typeSymbol == null) return null;

            foreach (var interfaceSymbol in typeSymbol.AllInterfaces)
            {
                if (interfaceSymbol.Name == "IRequestHandler" && interfaceSymbol.TypeArguments.Length == 2)
                {
                    var requestType = interfaceSymbol.TypeArguments[0];
                    var responseType = interfaceSymbol.TypeArguments[1];

                    return new HandlerInfo(
                        typeSymbol.ToDisplayString(),
                        requestType.ToDisplayString(),
                        responseType.ToDisplayString(),
                        typeSymbol.ContainingNamespace.ToDisplayString()
                    );
                }
            }

            return null;
        }

        private static void Execute(SourceProductionContext context, System.Collections.Immutable.ImmutableArray<HandlerInfo?> handlers)
        {
            if (handlers.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Mediator.Abstractions;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine("namespace Mediator.Generated;");
            sb.AppendLine();
            sb.AppendLine("public static class MediatorRegistrationExtensions");
            sb.AppendLine("{");
            sb.AppendLine("    public static IServiceCollection AddGeneratedMediator(this IServiceCollection services)");
            sb.AppendLine("    {");
            sb.AppendLine("        services.AddScoped<IMediator, GeneratedMediator>();");

            var validHandlers = handlers.Where(h => h != null).Cast<HandlerInfo>().ToList();

            foreach (var handler in validHandlers)
            {
                sb.AppendLine($"        services.AddScoped<IRequestHandler<{handler.RequestType}, {handler.ResponseType}>, {handler.HandlerType}>();");
            }

            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("public class GeneratedMediator : IMediator");
            sb.AppendLine("{");
            sb.AppendLine("    private readonly IServiceProvider _serviceProvider;");
            sb.AppendLine();
            sb.AppendLine("    public GeneratedMediator(IServiceProvider serviceProvider)");
            sb.AppendLine("    {");
            sb.AppendLine("        _serviceProvider = serviceProvider;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public Task<TResponse> SendAsync<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (request == null) throw new System.ArgumentNullException(nameof(request));");
            sb.AppendLine();

            foreach (var handler in validHandlers)
            {
                sb.AppendLine($"        if (request is {handler.RequestType} r{validHandlers.IndexOf(handler)})");
                sb.AppendLine("        {");
                sb.AppendLine($"            return (Task<TResponse>)(object)_serviceProvider.GetRequiredService<IRequestHandler<{handler.RequestType}, {handler.ResponseType}>>().HandleAsync(r{validHandlers.IndexOf(handler)}, cancellationToken);");
                sb.AppendLine("        }");
            }

            sb.AppendLine();
            sb.AppendLine("        throw new System.InvalidOperationException($\"No handler registered for request type {request.GetType().FullName}\");");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("MediatorGenerated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private record HandlerInfo(string HandlerType, string RequestType, string ResponseType, string Namespace);
    }
}

namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit { }
}
