using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Mediator.SourceGenerator
{
    [Generator]
    public class MediatorGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var handlerDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax { BaseList: not null },
                    transform: static (ctx, _) => GetHandlerInfo(ctx))
                .Where(static m => m is not null);

            var assemblyName = context.CompilationProvider.Select(static (c, _) => c.AssemblyName);
            
            var options = context.CompilationProvider.Select(static (c, _) => GetOptions(c));

            var combined = handlerDeclarations.Collect()
                .Combine(assemblyName)
                .Combine(options);

            context.RegisterSourceOutput(combined, Execute);
        }

        private static string GetOptions(Compilation compilation)
        {
            var attributeSymbol = compilation.GetTypeByMetadataName("Mediator.Abstractions.MediatorOptionsAttribute");
            if (attributeSymbol == null) return "Mediator.Generated";

            var assemblyAttribute = compilation.Assembly.GetAttributes()
                .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeSymbol));

            if (assemblyAttribute == null) return "Mediator.Generated";

            var namespaceArg = assemblyAttribute.NamedArguments
                .FirstOrDefault(kvp => kvp.Key == "Namespace");

            return namespaceArg.Value.Value?.ToString() ?? "Mediator.Generated";
        }

        private static HandlerInfo? GetHandlerInfo(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var model = context.SemanticModel;
            var typeSymbol = model.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (typeSymbol == null) return null;

            foreach (var interfaceSymbol in typeSymbol.AllInterfaces)
            {
                if (interfaceSymbol.Name == "IRequestHandler" && interfaceSymbol.TypeArguments.Length == 2)
                {
                    var requestType = interfaceSymbol.TypeArguments[0];
                    var responseType = interfaceSymbol.TypeArguments[1];

                    return new HandlerInfo(
                        typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        responseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    );
                }
            }

            return null;
        }

        private static void Execute(SourceProductionContext context, ((ImmutableArray<HandlerInfo?> Handlers, string? AssemblyName) Left, string GeneratedNamespace) input)
        {
            var handlers = input.Left.Handlers;
            var assemblyName = input.Left.AssemblyName ?? "UnknownAssembly";
            var generatedNamespace = input.GeneratedNamespace;

            if (assemblyName == "Mediator" || assemblyName == "Mediator.Abstractions")
            {
                return;
            }

            var validHandlers = handlers.Where(h => h != null).Cast<HandlerInfo>().ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Mediator.Abstractions;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
            sb.AppendLine("{");
            sb.AppendLine("    public static class MediatorRegistrationExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IServiceCollection AddMediator(this IServiceCollection services)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (services.Any(d => d.ServiceType == typeof(IMediator)))");
            sb.AppendLine("                return services;");
            sb.AppendLine();
            sb.AppendLine($"            services.AddScoped<IMediator, global::{generatedNamespace}.GeneratedMediator>();");
            
            foreach (var handler in validHandlers)
            {
                sb.AppendLine($"            services.AddScoped<IRequestHandler<{handler.RequestType}, {handler.ResponseType}>, {handler.HandlerType}>();");
            }

            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine($"namespace {generatedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    internal class GeneratedMediator : IMediator");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly IServiceProvider _serviceProvider;");
            sb.AppendLine();
            sb.AppendLine("        public GeneratedMediator(IServiceProvider serviceProvider)");
            sb.AppendLine("        {");
            sb.AppendLine("            _serviceProvider = serviceProvider;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public async Task<TResponse> SendAsync<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (request == null) throw new ArgumentNullException(nameof(request));");
            sb.AppendLine();

            foreach (var handler in validHandlers)
            {
                sb.AppendLine($"            if (request is {handler.RequestType} r{validHandlers.IndexOf(handler)})");
                sb.AppendLine("            {");
                sb.AppendLine($"                var result = await HandleAsync<{handler.RequestType}, {handler.ResponseType}>(r{validHandlers.IndexOf(handler)}, cancellationToken);");
                sb.AppendLine($"                return (TResponse)(object)result;");
                sb.AppendLine("            }");
            }

            sb.AppendLine();
            sb.AppendLine("            throw new InvalidOperationException($\"No handler registered for request type {request.GetType().FullName}\");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private async Task<TResponse> HandleAsync<TRequest, TResponse>(TRequest request, CancellationToken cancellationToken) where TRequest : IRequest<TResponse>");
            sb.AppendLine("        {");
            sb.AppendLine("            var handler = _serviceProvider.GetRequiredService<IRequestHandler<TRequest, TResponse>>();");
            sb.AppendLine("            var behaviors = _serviceProvider.GetServices<IPipelineBehaviour<TRequest, TResponse>>();");
            sb.AppendLine();
            sb.AppendLine("            RequestHandlerDelegate<TResponse> handlerDelegate = () => handler.HandleAsync(request, cancellationToken);");
            sb.AppendLine();
            sb.AppendLine("            var pipeline = behaviors.Aggregate(handlerDelegate, (next, behavior) => () => behavior.Handle(request, next, cancellationToken));");
            sb.AppendLine();
            sb.AppendLine("            return await pipeline();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("Mediator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private record HandlerInfo(string HandlerType, string RequestType, string ResponseType);
    }
}

namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit { }
}
