<Project Sdk="Microsoft.NET.Sdk">



    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Mediator.Tests"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mediator.Abstractions\Mediator.Abstractions.csproj" />
    </ItemGroup>

</Project>
